name: Deploy to EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy app on EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        # Guardar la clave SSH en un archivo temporal
        echo "$EC2_SSH_KEY" > temp_key.pem
        chmod 600 temp_key.pem

        # Ejecutar comandos remotos en EC2
        ssh -o StrictHostKeyChecking=no -i temp_key.pem $EC2_USER@$EC2_HOST << EOF
          set -e
          if [ ! -d "app-directory" ]; then
            git clone https://github.com/mazuluagac/TallerClasePrometheusGrafana.git app-directory
          fi
          cd app-directory
          git pull
          docker-compose down
          docker-compose up -d --build
        EOF

        # Eliminar la clave temporal
        rm -f temp_key.pem
